version: '3'
services:
    frontend:
        restart: unless-stopped
        build: ./frontend/bugdaddy/
        image: bugdaddy-frontend
        ports:
            - 80:80/tcp
            - 443:443/tcp
        environment:
            - CERTBOT_EMAIL
            - FQDN
            - IS_STAGING
        volumes:
            - letsencrypt:/etc/letsencrypt
    backend:
        restart: unless-stopped
        depends_on:
            - frontend
        build: .
        image: bugdaddy-backend
        expose:
            - 5000
        volumes:
            - "./db/:/usr/src/app/db/"
volumes:
    letsencrypt: