version: '3'
services:
    frontend:
        restart: unless-stopped
        build: ./frontend/bugdaddy/
        image: bugdaddy-frontend
        ports:
            - 8080:8080/tcp
    backend:
        restart: unless-stopped
        depends_on:
            - frontend
        build: .
        image: bugdaddy-backend
        expose:
            - 5000
        volumes:
            - "./backend/db/:/usr/src/app/db/"
        environment:
            - SECRET_ID=bugs.internal/config